default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: laxus
  password: laxus

development:
  <<: *default
  database: admin_dashboard_development

test:
  <<: *default
  database: admin_dashboard_test

production:
  <<: *default
  database: admin_dashboard_production
  username: laxus
  password: <%= ENV['ADMIN_DASHBOARD_DATABASE_PASSWORD'] %>